# Generated by Django 5.0.4 on 2025-05-26 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderlineitem',
            old_name='sauces',
            new_name='sauce',
        ),
    ]
