# Generated by Django 5.0.4 on 2025-05-26 09:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0002_rename_sauces_orderlineitem_sauce'),
        ('menu', '0002_auto_20250507_1348'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderlineitem',
            name='sauce',
        ),
        migrations.AddField(
            model_name='orderlineitem',
            name='sauce',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='menu.sauce'),
        ),
    ]
