# Generated by Django 5.0.4 on 2025-06-03 05:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_auto_20250507_1348'),
        ('reviews', '0002_like'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='menu_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='menu.menuitem'),
        ),
    ]
