# Generated by Django 3.2.25 on 2025-05-07 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.RemoveField(
            model_name='menuitem',
            name='spice_level',
        ),
        migrations.AddField(
            model_name='sauce',
            name='spice_level',
            field=models.CharField(choices=[('none', 'None'), ('mild', 'Mild'), ('medium', 'Medium'), ('hot', 'Hot'), ('extra-hot', 'Extra Hot')], default='none', max_length=20),
        ),
    ]
